spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=urban_micro_farm_app
spring.datasource.username=postgres
spring.datasource.password=Via@12345
spring.jpa.properties.hibernate.default_schema=${APP_SCHEMA:urban_micro_farm_app}

# Enable schema initialization ALWAYS - it runs before Hibernate
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# Tell Hibernate to create the schema if it doesn't exist
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# For local development: let Hibernate create/update missing tables based on entities
spring.jpa.hibernate.ddl-auto=create-drop

# Defer datasource initialization until after DDL
spring.jpa.defer-datasource-initialization=true

## JWT
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3VyZS0yNTYtYml0LWRlZi1rZXk=}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

# Jackson
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.default-property-inclusion=non_null

# MQTT
mqtt.broker=tcp://20.240.208.122:1883
mqtt.client-id=iot-test-client
mqtt.topic=farm/#

# ML
ml.wateringPrediction.url=https://waterthingy-hwg6h4gzevedfjc3.germanywestcentral-01.azurewebsites.net/api/predict-watering?code=ViXHI-UoUHEaMvxx9XCNu8gd3TtWe1VGbo-AkbFy2fkHAzFuANQb8Q==
ml.plantHealthPrediction.url=https://planthealthprediction-hwg6h4gzevedfjc3.germanywestcentral-01.azurewebsites.net/api/predict-plant-health?code=VjXHI-UoUHEaMvxx9XCNu8gd3TtWe1VGbo-AkbFy2fkHAzFuANQb8Q==